apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrix-choreography-seed
spec:
  replicas: 1
  selector:
    matchLabels:
      component: matrix-choreography-seed
  template:
    metadata:
      labels:
        component: matrix-choreography-seed
    spec:
      containers:
        - name: matrix-choreography-seed
          image: akka-matrix/matrix-choreography
          imagePullPolicy: IfNotPresent
          command: ["java", "-jar",  "/app/target/topology-1.0-SNAPSHOT.jar"]
          volumeMounts:
            - name: choreography-setup
              mountPath: /root/.actorchoreography
          ports:
            - containerPort: 2000
            - containerPort: 2222
            - containerPort: 5149
          env:
            - name: EXTERNAL_POD_IP
              value: "$(MATRIX_CHOREOGRAPHY_SEED_SERVICE_HOST)"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SEED_DOMAIN
              value: "$(MATRIX_CHOREOGRAPHY_SEED_SERVICE_HOST)"
            - name: SEED_PORT
              value: "5149"
          terminationMessagePolicy: FallbackToLogsOnError
      volumes:
        - name: choreography-setup
          hostPath:
            path: /Users/etulika/Projects/akka-block-manager/test-data/node1/.actorchoreography

---

kind: Service
apiVersion: v1
metadata:
  name: matrix-choreography-seed
spec:
  ports:
    - name: api
      port: 2001
      targetPort: 2000
    - name: actor
      port: 5149
      targetPort: 5149
    - name: management
      port: 2222
      targetPort: 2222
  selector:
    component: matrix-choreography-seed
  type: LoadBalancer
  externalTrafficPolicy: Local

---


kind: Deployment
apiVersion: apps/v1
metadata:
  name: matrix-choreography-1
spec:
  replicas: 1
  selector:
    matchLabels:
      component: matrix-choreography-1
  template:
    metadata:
      labels:
        component: matrix-choreography-1
    spec:
      containers:
        - name: matrix-choreography
          image: akka-matrix/matrix-choreography
          imagePullPolicy: IfNotPresent
          command: ["java", "-jar",  "/app/target/topology-1.0-SNAPSHOT.jar"]
          volumeMounts:
            - name: choreography-setup
              mountPath: /root/.actorchoreography
          ports:
            - containerPort: 2000
            - containerPort: 2222
            - containerPort: 5149
          env:
            - name: EXTERNAL_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SEED_DOMAIN
              value: "$(MATRIX_CHOREOGRAPHY_SEED_SERVICE_HOST)"
            - name: SEED_PORT
              value: "5149"
          terminationMessagePolicy: FallbackToLogsOnError
      volumes:
        - name: choreography-setup
          hostPath:
            path: /Users/etulika/Projects/akka-block-manager/test-data/node2/.actorchoreography

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: matrix-choreography-2
spec:
  replicas: 1
  selector:
    matchLabels:
      component: matrix-choreography-2
  template:
    metadata:
      labels:
        component: matrix-choreography-2
    spec:
      containers:
        - name: matrix-choreography
          image: akka-matrix/matrix-choreography
          imagePullPolicy: IfNotPresent
          command: ["java", "-jar",  "/app/target/topology-1.0-SNAPSHOT.jar"]
          volumeMounts:
            - name: choreography-setup
              mountPath: /root/.actorchoreography
          ports:
            - containerPort: 2000
            - containerPort: 2222
            - containerPort: 5149
          env:
            - name: EXTERNAL_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SEED_DOMAIN
              value: "$(MATRIX_CHOREOGRAPHY_SEED_SERVICE_HOST)"
            - name: SEED_PORT
              value: "5149"
          terminationMessagePolicy: FallbackToLogsOnError
      volumes:
        - name: choreography-setup
          hostPath:
            path: /Users/etulika/Projects/akka-block-manager/test-data/node3/.actorchoreography